id: P010692
initial_creation_type: ocr
source_metadata:
  id: bdr:W18
  title: སྒྲུབ་ཐབས་འདོད་འཇོའི་འབུམ་བཟང་།
  author: ''
  volumes:
    e6b92ea7445f411aad6dd30fb35115e9:
      image_group_id: I1735
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
    1be5027dcdba44a3a48977b20974c985:
      image_group_id: I1736
      title: ''
      volume_number: 2
      total_pages: 388
      base_file: v002.txt
