id: I7F5826A6
legacy_id: P010692
ocr_import_info:
  bdrc_scan_id: W18
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T08:07:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:09:19.156580+00:00'
last_modified: 2022-08-30 23:10:10.021628
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W18
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW18
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲུབ་ཐབས་འདོད་འཇོའི་འབུམ་བཟང་།
  author: སྨིན་གླིང་ལོ་ཆེན་དྷརྨ་ཤྲཱི།
statistics:
  ocr_word_mean_confidence_index: 0.7257265786928603
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1735:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1735
      total_pages: 418
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1735.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7388931587909603
    legacy_id: v001
  I1736:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1736
      total_pages: 388
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1736.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7111859861640683
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
